instaclone/urls.py
from django.contrib import admin
from django.urls import path, include

from  django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.explore, name='explore'),
    path('timeline', views.timeline, name='timeline'),
    path('upload-photo/', views.uploadPhoto, name='upload-photo'),
    path('post-detail/<str:pk>/', views.postDetail, name='post-detail'),
    path('add-comment/<str:pk>/', views.addComment, name='add-comment'),
    path('add-like/<str:pk>/', views.addLike, name='add-like'),
    path('follow-user/<str:followee_pk>/', views.followUser, name='follow-user'),
    path('un-follow-user/<str:followee_pk>/', views.unFollowUser, name='un-follow-user'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    post_image = models.ImageField(upload_to='posts/')
    tag = models.ForeignKey(
        'Tag', on_delete=models.CASCADE, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def save_post(self):
        '''
        Method that saves the Post object
        '''
        self.save()

    @classmethod
    def update_post(cls, record_id, update_value):
        '''
        Method that Updates a post record
        '''
        cls.objects.filter(pk=record_id).update(title=update_value)

    @classmethod
    def delete_post(cls, post_id):
        '''
        Method that deletes a post
        '''
        post = cls.objects.filter(id=post_id)
        post.delete()

    def __str__(self):
        return self.description

    class Meta:
        ordering = ['-created']


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def save_tag(self):
        '''
        Method that saves the Tag object
        '''
        self.save()

    @classmethod
    def update_tag(cls, record_id, update_value):
        '''
        Method that Updates a tag record
        '''
        cls.objects.filter(pk=record_id).update(name=update_value)

    @classmethod
    def delete_tag(cls, tag_id):
        '''
        Method that deletes a tag
        '''
        tag = cls.objects.filter(id=tag_id)
        tag.delete()

    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    comment = models.CharField(max_length=200, blank=True, null=True)
    post = models.ForeignKey(
        'Post', on_delete=models.CASCADE, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def save_comment(self):
        '''
        Method that saves the Comment object
        '''
        self.save()

    @classmethod
    def update_comment(cls, record_id, update_value):
        '''
        Method that Updates a comment record
        '''
        cls.objects.filter(pk=record_id).update(comment=update_value)

    @classmethod
    def delete_comment(cls, comment_id):
        '''
        Method that deletes a comment
        '''
        comment = cls.objects.filter(id=comment_id)
        comment.delete()

    def __str__(self):
        return self.comment


class Like(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    post = models.ForeignKey(
        'Post', on_delete=models.CASCADE, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def save_like(self):
        '''
        Method that saves the Like object
        '''
        self.save()

    @classmethod
    def update_like(cls, record_id, update_value):
        '''
        Method that Updates a like record
        '''
        cls.objects.filter(id=record_id).update(post=update_value)

    @classmethod
    def delete_like(cls, like_id):
        '''
        Method that deletes a like
        '''
        like = cls.objects.filter(id=like_id)
        like.delete()

    def __str__(self):
        return self.post.id


class Follow(models.Model):
    follower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="following")
    followee = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="followers")
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def save_follow(self):
        '''
        Method that saves the Follow object
        '''
        self.save()
    
    @classmethod
    def delete_follow(cls, follow_id):
        '''
        Method that deletes a follow
        '''
        follow = cls.objects.filter(id=follow_id)
        follow.delete()

posts/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post,Comment,Like

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','description', 'post_image', 'tag']
        widgets ={
            'tag': forms.Select()
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
    
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'bg-transparent max-h-10 shadow-none'})

class LikeForm(forms.ModelForm):
    class Meta:
        model = Like()
        fields = ['user','post']

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import JsonResponse

from users.models import Profile
from .models import Post, Tag, Comment, Like, Follow
from .forms import PostForm, CommentForm, LikeForm
from .serializer import CommentSerializer
from .utils import fetchComments
# Create your views here.


@login_required(login_url='login')
def timeline(request):
    profile = request.user.profile
    posts = []
    to_follow = []
    
    # Get posts for users that are being followed
    for user in Follow.objects.filter(follower=request.user):
        for post in Post.objects.filter(user=user.followee):
            posts.append(post)

    # Posts for the logged-in user
    for post in Post.objects.all():
        if post.user == request.user:
            posts.append(post)
    
    # Get users to follow
    for user in User.objects.all():
        if Follow.objects.filter(followee=user, follower=request.user).count() == 0 and user != request.user:
            to_follow.append(user)


    context = {
        'profile': profile,
        'posts': posts,
        'uploadForm': PostForm(),
        'commentForm': CommentForm(),
        'to_follow': to_follow,
        'user_followers_count': Follow.objects.filter(followee=request.user).count(),
        'user_following_count': Follow.objects.filter(follower=request.user).count(),
    }
    return render(request, 'posts/timeline.html', context)


@login_required(login_url='login')
def explore(request):
    profile = request.user.profile
    posts = Post.objects.all()
    context = {
        'profile': profile,
        'posts': posts,
        'uploadForm': PostForm(),
        'tags': Tag.objects.all(),
        'commentForm': CommentForm(),
        'user_followers_count': Follow.objects.filter(followee=request.user).count(),
        'user_following_count': Follow.objects.filter(follower=request.user).count(),
    }

    return render(request, 'posts/explore.html', context)


@login_required(login_url='login')
def uploadPhoto(request):
    user = request.user
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        upload = form.save(commit=False)
        upload.user = user
        upload.save()

    return redirect(request.META.get('HTTP_REFERER'))


@login_required(login_url='login')
def postDetail(request, pk):
    post = Post.objects.get(id=pk)
    data = {
        'id': post.id,
        'post_image': post.post_image.url,
        'description': post.description,
        'tag': post.tag.name,
        'user_image': post.user.profile.profile_image.url,
        'user_name': post.user.profile.name,
        'description': post.description,
        'comments': fetchComments(request, post)
    }
    return JsonResponse(data)


@login_required(login_url='login')
def addComment(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(id=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()

    return redirect(request.META.get('HTTP_REFERER'))


@login_required(login_url='login')
def addLike(request, pk):
    post = Post.objects.get(id=pk)
    user = request.user
    data = {'status': False}

    if Like.objects.filter(post=post, user=user).count() == 0:
        like = Like(user=user, post=post)
        like.save()
        data['status'] = True

        likes = Like.objects.filter(post=post)
        data['num_likes'] = len(likes)

    return redirect(request.META.get('HTTP_REFERER'))


@login_required(login_url='login')
def followUser(request, followee_pk):
    follower = request.user
    followee = User.objects.get(id=followee_pk)
    
    if Follow.objects.filter(followee=followee, follower=follower).count() == 0:
        new_follow = Follow(followee=followee, follower=follower)
        new_follow.save()

    return redirect(request.META.get('HTTP_REFERER'))

@login_required(login_url='login')
def unFollowUser(request, followee_pk):
    follower = request.user
    followee = User.objects.get(id=followee_pk)
    
    Follow.objects.filter(followee=followee, follower=follower).delete()

    return redirect(request.META.get('HTTP_REFERER'))

posts/templates/posts/explore.html
{% extends 'base.html' %}
{% block content %}
    <div class="container m-auto">

        <h1 class="lg:lg:text-2xl text-lg text-lg font-extrabold leading-none text-gray-900 tracking-tight mt-3"> Explore </h1>

        <div class="lg:m-0 -mx-5 flex justify-between items-center py-2 relative space-x-3 dark-tabs" uk-sticky="cls-active: bg-gray-100 bg-opacity-95; media : @m ; media @m">
            <div class="flex overflow-x-scroll lg:overflow-hidden lg:pl-0 pl-5 space-x-3 lg:py-2">
                {% for tag in tags %}
                    <a href="#" class="bg-white py-2 px-4 rounded inline-block font-bold shadow"> {{tag}}</a>
                {% endfor %}
            </div>
        </div>
        
        <div class="grid lg:grid-cols-4 grid-cols-2 gap-2 hover:text-yellow-700 uk-link-reset">
            {% for post in posts %}
                {% if forloop.counter == 1%}
                    <div>
                        <div class="bg-red-400 max-w-full lg:h-64 h-4 rounded-md relative overflow-hidden uk-transition-toggle shadow-sm"> 
                            <a href="#story-modal" uk-toggle data-postid="{{post.id}}" class="user-post-detail">
                                <img src="{{post.post_image.url}}" class="w-full h-full absolute object-cover inset-0">
                            </a>
                            <div class="absolut absolute bottom-0 flex items-center justify-between px-4 py-3 space-x-2 text-white w-full custom-overly1">   
                                <a href="#">{{post.user.profile.name}} </a>  
                                <div class="flex space-x-3">  
                                <a data-postid="{{post.id}}" href="{% url 'add-like' post.id%}" class="flex items-center like-post"> <ion-icon name="heart" class="mr-1 md hydrated" role="img" aria-label="heart"></ion-icon>  {{post.like_set.all|length}} </a>
                                </div>        
                            </div>
                        </div>
                    </div>
                {% elif forloop.counter == 2 %}
                    <div class="lg:col-span-2 lg:row-span-2">
                        <div class="bg-pink-400 h-full max-w-full overflow-hidden relative rounded-md uk-transition-toggle shadow-sm"> 
                            <a href="#story-modal" uk-toggle data-postid="{{post.id}}" class="user-post-detail">
                                <img src="{{post.post_image.url}}" class="w-full h-full absolute object-cover inset-0 transform scale-125">
                            </a>
                            <div class="absolut absolute bottom-0 p-6 space-y-2 text-white w-full custom-overly1 uk-light lg:block hidden">   
                                <div class="flex flex-1 items-center space-x-2">
                                    <a href="#" class="flex items-center">
                                        <div class="bg-gradient-to-tr from-yellow-600 to-pink-600 p-1 rounded-full transform -rotate-2 hover:rotate-3 transition hover:scale-105 m-0.5 mr-2">
                                            <img src="{{post.user.profile.profile_image.url}}" class="bg-gray-200 border border-white rounded-full w-8">
                                        </div>
                                        {{post.user.profile.name}}  
                                    </a>
                                    <div class="flex space-x-3">
                                        <a data-postid="{{post.id}}"  href="{% url 'add-like' post.id%}" class="flex items-center like-post">
                                            <ion-icon name="heart" class="mr-1 md hydrated" role="img" aria-label="heart"></ion-icon> {{post.like_set.all|length}}
                                        </a>
                                    </div>
                                </div>
                                <h1 class="font-bold text-3xl"> {{post.title}}</h1>
                                <p>{{post.description}}</p>
                            </div>
                        </div>
                    </div>
                {% elif forloop.counter == 3 %}
                    <div>
                        <div class="bg-green-400 max-w-full lg:h-64 h-40 rounded-md relative overflow-hidden uk-transition-toggle shadow-sm"> 
                            <a href="#story-modal" uk-toggle data-postid="{{post.id}}" class="user-post-detail">
                                <img src="{{post.post_image.url}}" class="w-full h-full absolute object-cover inset-0">
                            </a>
                            <div class="absolut absolute bottom-0 flex items-center justify-between px-4 py-3 space-x-2 text-white w-full custom-overly1">   
                                <a href="#">{{post.user.profile.name}}  </a>  
                                <div class="flex space-x-3">  
                                <a data-postid="{{post.id}}"  href="{% url 'add-like' post.id%}" class="flex items-center like-post"> <ion-icon name="heart" class="mr-1 md hydrated" role="img" aria-label="heart"></ion-icon>  {{post.like_set.all|length}} </a>
                                </div>        
                            </div>
                        </div>
                    </div>
                {% elif forloop.counter == 4 %}
                    <div>
                        <div class="bg-yellow-400 max-w-full lg:h-64 h-40 rounded-md relative overflow-hidden shadow-sm"> 
                            <a href="#story-modal" uk-toggle data-postid="{{post.id}}" class="user-post-detail">
                                <img src="{{post.post_image.url}}" class="w-full h-full absolute object-cover inset-0 object-cover object-left">
                            </a>
                            <div class="absolut absolute bottom-0 flex items-center justify-between px-4 py-3 space-x-2 text-white w-full custom-overly1">   
                                <a href="#">{{post.user.profile.name}}  </a>  
                                <div class="flex space-x-3">  
                                <a data-postid="{{post.id}}"  href="{% url 'add-like' post.id%}" class="flex items-center like-post"> <ion-icon name="heart" class="mr-1 md hydrated" role="img" aria-label="heart"></ion-icon>  {{post.like_set.all|length}} </a>
                                </div>        
                            </div>
                        </div>
                    </div>
                {% elif forloop.counter == 5 %}
                    <div>
                        <div class="bg-purple-400 max-w-full lg:h-64 h-40 rounded-md relative overflow-hidden shadow-sm"> 
                            <a href="#story-modal" uk-toggle data-postid="{{post.id}}" class="user-post-detail">
                                <img src="{{post.post_image.url}}" class="w-full h-full absolute object-cover inset-0">
                            </a>
                            <div class="absolut absolute bottom-0 flex items-center justify-between px-4 py-3 space-x-2 text-white w-full custom-overly1">   
                                <a href="#">{{post.user.profile.name}} </a>  
                                <div class="flex space-x-3">  
                                <a data-postid="{{post.id}}"  href="{% url 'add-like' post.id%}" class="flex items-center like-post"> <ion-icon name="heart" class="mr-1 md hydrated" role="img" aria-label="heart"></ion-icon>  {{post.like_set.all|length}} </a>
                                </div>        
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div>
                        <div class="bg-blue-400 max-w-full lg:h-64 h-40 rounded-md relative overflow-hidden shadow-sm"> 
                            <a href="#story-modal" uk-toggle data-postid="{{post.id}}" class="user-post-detail">
                                <img src="{{post.post_image.url}}" class="w-full h-full absolute object-cover inset-0">
                            </a>
                            <div class="absolut absolute bottom-0 flex items-center justify-between px-4 py-3 space-x-2 text-white w-full custom-overly1">   
                                <a href="#">{{post.user.profile.name}}  </a>  
                                <div class="flex space-x-3">  
                                <a data-postid="{{post.id}}"  href="{% url 'add-like' post.id%}" class="flex items-center like-post"> <ion-icon name="heart" class="mr-1 md hydrated" role="img" aria-label="heart"></ion-icon>  {{post.like_set.all|length}} </a>
                                </div>        
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}    
        </div>
    </div>
{% endblock content %}